FROM node:16.15.1-alpine
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY . ./
RUN npm install @mui/icons-material
RUN npm install @material-ui/core@4.12.4
RUN npm install @material-ui/types
RUN npm install @types/react
RUN npm install -g npm@8.19.2
RUN npm install  
RUN npm install react-scripts@3.4.1 -g 

CMD ["npm", "run", "start"]