# ==== CONFIGURE =====
# Use a Node 16 base image
FROM node:16-alpine

WORKDIR /usr/local/bin/web

COPY . /usr/local/bin/web/

RUN yarn install --prefix client



RUN yarn run build
# ==== RUN =======
CMD ["npm", "start"]